apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-frontend-7
  labels:
    app: my-app-deployment-frontend-7
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: my-app-deployment-frontend-7
  template:
    metadata:
      labels:
        app: my-app-deployment-frontend-7
    spec:
      containers:
        - name: my-app-deployment-frontend-7
          image: `${process.env.REACT_APP_DEPLOYMENT_FRONTEND_IMAGE}`
          env:
            - name: DBURL
              value: "https://noventiq-exercise-db-default-rtdb.asia-southeast1.firebasedatabase.app/"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment-frontend-7
spec:
  selector:
    app: my-app-deployment-frontend-7
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-backend-7
  labels:
    app: my-app-deployment-backend-7
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: my-app-deployment-backend-7
  template:
    metadata:
      labels:
        app: my-app-deployment-backend-7
    spec:
      containers:
        - name: my-app-deployment-backend-7
          image: `${REACT_APP_DEPLOYMENT_BACKEND_IMAGE}`
          env:
            - name: DBURL
              value: "https://noventiq-exercise-db-default-rtdb.asia-southeast1.firebasedatabase.app/"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment-backend-7
spec:
  selector:
    app: my-app-deployment-backend-7
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
