version: '3.8'

services:
  ndserver:
    environment: 
      DB_URL: "https://noventiq-exercise-db-default-rtdb.asia-southeast1.firebasedatabase.app/"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3001:3001
  ndapp:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
