apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-frontend-7
  labels:
    app: my-app-deployment-frontend-7
spec:
  replicas: #replicaNum#
  selector:
    matchLabels:
      app: my-app-deployment-frontend-7
  template:
    metadata:
      labels:
        app: my-app-deployment-frontend-7
    spec:
      containers:
        - name: my-app-deployment-frontend-7
          image: myappacr1998001.azurecr.io/sampleapp-002:#appTag#
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment-frontend-7
spec:
  selector:
    app: my-app-deployment-frontend-7
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-backend-7
  labels:
    app: my-app-deployment-backend-7
spec:
  replicas: #replicaNum#
  selector:
    matchLabels:
      app: my-app-deployment-backend-7
  template:
    metadata:
      labels:
        app: my-app-deployment-backend-7
    spec:
      containers:
        - name: my-app-deployment-backend-7
          image: myappacr1998001.azurecr.io/sampleapp-002:#serverTag#
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment-backend-7
spec:
  selector:
    app: my-app-deployment-backend-7
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
