apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontEnd }}
  labels:
    app: {{ .Values.frontEnd }}
spec:
  replicas: #replicaNum#
  selector:
    matchLabels:
      app: {{ .Values.frontEnd }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontEnd }}
    spec:
      containers:
        - name: {{ .Values.frontEnd }}
          image: #acrLoginServer#/#imageRepo-2#:#appTag-2#
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontEnd }}
spec:
  selector:
    app: {{ .Values.frontEnd }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backEnd }}
  labels:
    app: {{ .Values.backEnd }}
spec:
  replicas: #replicaNum#
  selector:
    matchLabels:
      app: {{ .Values.backEnd }}
  template:
    metadata:
      labels:
        app: {{ .Values.backEnd }}
    spec:
      containers:
        - name: {{ .Values.backEnd }}
          image: #acrLoginServer#/#imageRepo-2#:#serverTag-2#
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backEnd }}
spec:
  selector:
    app: {{ .Values.backEnd }}
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
